name: Java CI/CD with Maven and EC2 Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Use your EC2 instance as the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Restart Application on EC2
        run: |
          echo "Stopping existing application..."
          pkill -f "java -jar" || echo "No process found."
          echo "Starting new application..."
          nohup java -jar target/*.jar > app.log 2>&1 &
